# Generated by Django 4.1.4 on 2022-12-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='abc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
